In [89]:
import pandas as pd
import numpy as np
from fredapi import Fred
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt

# Insert your FRED API key
fred = Fred(api_key='7c555b88e31520b011cc33e23aba5fb8')

# Define date range
start_date = '2009-11-01'
end_date = '2024-12-31'

# Target variable: WTI crude oil price
wti = fred.get_series('DCOILWTICO', start_date, end_date)

In [ ]:
#inventories = fred.get_series('WCESTUS1', start_date, end_date)

ValueError: Bad Request.  The series does not exist.

In [90]:
import yfinance as yf

start_date = "2009-11-01"
end_date = "2024-12-31"

# Gold futures (COMEX)
gold = yf.download("GC=F", start=start_date, end=end_date)

# Use adjusted close (or Close)
gold_series = gold["Close"]["GC=F"]

print(gold_series)

[*********************100%***********************]  1 of 1 completed

Date
2009-11-02    1053.400024
2009-11-03    1084.300049
2009-11-04    1086.699951
2009-11-05    1088.699951
2009-11-06    1095.099976
                 ...
2024-12-23    2612.300049
2024-12-24    2620.000000
2024-12-26    2638.800049
2024-12-27    2617.199951
2024-12-30    2606.100098
Name: GC=F, Length: 3812, dtype: float64

In [91]:
ovx = yf.download("^OVX", start="2009-11-01", end="2024-12-31")
oil_volatility = ovx['Close']['^OVX']
oil_volatility

[*********************100%***********************]  1 of 1 completed

Date
2009-11-02    41.779999
2009-11-03    41.580002
2009-11-04    40.599998
2009-11-05    38.980000
2009-11-06    38.700001
                ...
2024-12-23    30.160000
2024-12-24    30.350000
2024-12-26    30.010000
2024-12-27    30.209999
2024-12-30    30.770000
Name: ^OVX, Length: 3815, dtype: float64

In [93]:
# Interest Rates
y3 = fred.get_series('DGS3', start_date, end_date)   # 3-Year Treasury
y10 = fred.get_series('DGS10', start_date, end_date) # 10-Year Treasury

# Yield Spread (10Y - 3Y)
yield_spread = y10 - y3

# Industrial Production
indpro = fred.get_series('INDPRO', "2009-11-01", end_date)

In [94]:
yield_spread

2009-11-02    2.01
2009-11-03    2.04
2009-11-04    2.11
2009-11-05    2.13
2009-11-06    2.14
              ...
2024-12-25     NaN
2024-12-26    0.23
2024-12-27    0.26
2024-12-30    0.26
2024-12-31    0.31
Length: 3957, dtype: float64

In [95]:
indpro

2009-11-01     88.0221
2009-12-01     88.3793
2010-01-01     89.3426
2010-02-01     89.6779
2010-03-01     90.2928
                ...
2024-08-01    100.4309
2024-09-01     99.8084
2024-10-01     99.4695
2024-11-01     99.2925
2024-12-01    100.3273
Length: 182, dtype: float64

In [96]:
# S&P 500 index
#sp500 = fred.get_series('SP500', start_date, end_date)

# VIX volatility index
vix = fred.get_series('VIXCLS', start_date, end_date)

# USD index (Trade Weighted Dollar Index)
usd = fred.get_series('DTWEXBGS', start_date, end_date)

In [97]:
sp500 = yf.download("^GSPC", start=start_date, end=end_date)
sp500=sp500["Close"]['^GSPC']
sp500

[*********************100%***********************]  1 of 1 completed

Date
2009-11-02    1042.880005
2009-11-03    1045.410034
2009-11-04    1046.500000
2009-11-05    1066.630005
2009-11-06    1069.300049
                 ...
2024-12-23    5974.069824
2024-12-24    6040.040039
2024-12-26    6037.589844
2024-12-27    5970.839844
2024-12-30    5906.939941
Name: ^GSPC, Length: 3815, dtype: float64

- The S&P 500 (Standard & Poor's 500 Index) is a market-capitalization-weighted index tracking 500 of the largest publicly traded U.S. companies. It is a premier benchmark for the overall health of the US economy and stock market, representing roughly 80% of the total market value.
- The CBOE Volatility Index (VIX) is a real-time market index that acts as a "fear gauge," measuring expected 30-day volatility for the S&P 500 index. It predicts market risk and investor sentiment by tracking options prices, usually moving inversely to the S&P 500—rising during uncertainty and falling during stability
- West Texas Intermediate (WTI) is a high-quality, light, and sweet crude oil that serves as a primary benchmark for oil pricing in the United States
- The U.S. Dollar Index (DXY) is a measure of the value of the U.S. dollar relative to a basket of six major foreign currencies: the Euro (EUR), Japanese Yen (JPY), British Pound (GBP), Canadian Dollar (CAD), Swedish Krona (SEK), and Swiss Franc (CHF)
- Crude oil inventory refers to the total stock of unrefined petroleum currently stored in tanks, pipelines, and terminals by producing nations, refiners, and commercial operators.

In [11]:
# The raw text you provided
data = '''"STUB_1","3/13/26","3/6/26","Difference","3/14/25","Percent Change","3/15/24","Percent Change"
"Crude Oil","864.701","858.545","6.156","832.831","3.800","807.348","7.100"
"Commercial (Excluding SPR)","449.259","443.103","6.156","436.968","2.800","445.042","0.900"
"East Coast (PADD 1)","8.355","8.039","0.316","8.421","-0.800","8.318","0.400"
"Midwest (PADD 2)","109.954","109.038","0.916","105.471","4.300","116.664","-5.800"
"Cushing","27.524","26.580","0.944","23.460","17.300","31.433","-12.400"
"Gulf Coast (PADD 3)","260.245","257.352","2.893","252.319","3.100","247.865","5.000"
"Rocky Mountain (PADD 4)","25.155","24.463","0.693","24.712","1.800","26.303","-4.400"
"West Coast (PADD 5)","45.550","44.212","1.338","46.045","-1.100","45.891","-0.700"
"Alaska In-Transit","4.164","2.103","2.061","3.583","16.200","2.545","63.600"
"SPR","415.442","415.442","0.000","395.863","4.900","362.306","14.700"
"Total Motor Gasoline","244.040","249.476","-5.436","240.574","1.400","230.773","5.700"
"Reformulated","0.030","0.014","0.016","0.029","3.400","0.024","25.000"
"Conventional","12.904","14.261","-1.357","14.271","-9.600","14.831","-13.000"
"Blending Components","231.106","235.201","-4.095","226.274","2.100","215.919","7.000"
"Fuel Ethanol","26.407","25.580","0.827","26.575","-0.600","26.009","1.500"
"Kerosene-Type Jet Fuel","43.623","41.245","2.377","43.173","1.000","40.447","7.900"
"Distillate Fuel Oil","116.904","119.431","-2.527","114.783","1.800","118.522","-1.400"
"15 ppm sulfur and Under","105.084","107.621","-2.537","106.318","-1.200","108.072","-2.800"
"> 15 ppm to 500 ppm sulfur","4.017","3.927","0.090","2.837","41.600","2.678","50.000"
"> 500 ppm sulfur","7.802","7.883","-0.081","5.628","38.600","7.771","0.400"
"Residual Fuel Oil","25.075","24.182","0.893","23.406","7.100","29.742","-15.700"
"Propane/Propylene","72.485","71.675","0.810","43.349","67.200","52.207","38.800"
"Other Oils ","289.577","292.233","-2.656","272.084","6.400","269.205","7.600"
"Unfinished Oils","82.289","83.186","-0.897","86.032","-4.400","88.736","-7.300"
"Total Stocks (Including SPR)","1,682.813","1,682.368","0.444","1,596.776","5.400","1,574.253","6.900"
"Total Stocks (Excluding SPR)","1,267.371","1,266.926","0.444","1,200.913","5.500","1,211.947","4.600"
'''

# Save it to a CSV file
with open("crude_oil_inventory.csv", "w", newline='') as f:
    f.write(data)

print("CSV file saved as crude_oil_inventory.csv")

CSV file saved as crude_oil_inventory.csv

In [50]:
data

,WTI,SP500,VIX,USD,Gold,Yield,Oil_Volatility
2010-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-04,81.52,1132.989990,20.04,92.3566,1117.699951,2.19,35.439999
2010-01-05,81.74,1136.520020,19.35,92.2236,1118.099976,2.20,34.270000
2010-01-06,83.12,1137.140015,19.16,92.0941,1135.900024,2.25,34.400002
2010-01-07,82.60,1141.689941,19.06,92.3684,1133.099976,2.23,33.610001
...,...,...,...,...,...,...,...
2024-12-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-12-26,70.38,6037.589844,14.73,128.3329,2638.800049,0.23,30.010000
2024-12-27,71.28,5970.839844,15.95,128.4500,2617.199951,0.26,30.209999
2024-12-30,71.73,5906.939941,17.40,128.8205,2606.100098,0.26,30.770000
2024-12-31,72.44,NaN,17.35,129.2775,NaN,0.31,NaN

In [99]:
for df in [wti, sp500, vix, usd, gold_series, yield_spread, oil_volatility]:
    df.index = pd.to_datetime(df.index)
    df.sort_index(inplace=True)

In [100]:
data = pd.concat(
    [wti, sp500, vix, usd, gold_series, yield_spread, oil_volatility],
    axis=1,
    join='outer'
)

In [101]:
data.columns = ['WTI', 'SP500', 'VIX', 'USD', "Gold", "Yield", "Oil_Volatility"]
data

,WTI,SP500,VIX,USD,Gold,Yield,Oil_Volatility
2009-11-02,78.08,1042.880005,29.78,92.4501,1053.400024,2.01,41.779999
2009-11-03,79.58,1045.410034,28.81,92.9037,1084.300049,2.04,41.580002
2009-11-04,80.30,1046.500000,27.72,92.3725,1086.699951,2.11,40.599998
2009-11-05,79.64,1066.630005,25.43,92.3437,1088.699951,2.13,38.980000
2009-11-06,77.40,1069.300049,24.19,92.3848,1095.099976,2.14,38.700001
...,...,...,...,...,...,...,...
2024-12-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-12-26,70.38,6037.589844,14.73,128.3329,2638.800049,0.23,30.010000
2024-12-27,71.28,5970.839844,15.95,128.4500,2617.199951,0.26,30.209999
2024-12-30,71.73,5906.939941,17.40,128.8205,2606.100098,0.26,30.770000
2024-12-31,72.44,NaN,17.35,129.2775,NaN,0.31,NaN

In [102]:
indpro_release = indpro.copy()

# shift to end of month
indpro_release.index = indpro_release.index + pd.offsets.MonthEnd(0)

# add ~15 days release lag (approximation)
indpro_release.index = indpro_release.index + pd.Timedelta(days=15)

data['INDPRO'] = indpro_release.reindex(data.index).ffill()

In [103]:
indpro_release

2009-12-15     88.0221
2010-01-15     88.3793
2010-02-15     89.3426
2010-03-15     89.6779
2010-04-15     90.2928
                ...
2024-09-15    100.4309
2024-10-15     99.8084
2024-11-15     99.4695
2024-12-15     99.2925
2025-01-15    100.3273
Length: 182, dtype: float64

In [ ]:
data.index.name = "Date"
data

,WTI,SP500,VIX,USD,Gold,Yield,Oil_Volatility,INDPRO
Date,,,,,,,,
2009-11-02,78.08,1042.880005,29.78,92.4501,1053.400024,2.01,41.779999,NaN
2009-11-03,79.58,1045.410034,28.81,92.9037,1084.300049,2.04,41.580002,NaN
2009-11-04,80.30,1046.500000,27.72,92.3725,1086.699951,2.11,40.599998,NaN
2009-11-05,79.64,1066.630005,25.43,92.3437,1088.699951,2.13,38.980000,NaN
2009-11-06,77.40,1069.300049,24.19,92.3848,1095.099976,2.14,38.700001,NaN
...,...,...,...,...,...,...,...,...
2024-12-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99.4695
2024-12-26,70.38,6037.589844,14.73,128.3329,2638.800049,0.23,30.010000,99.4695
2024-12-27,71.28,5970.839844,15.95,128.4500,2617.199951,0.26,30.209999,99.4695
2024-12-30,71.73,5906.939941,17.40,128.8205,2606.100098,0.26,30.770000,99.4695
2024-12-31,72.44,NaN,17.35,129.2775,NaN,0.31,NaN,99.4695

In [111]:
#get data just from 2010
data=data.loc[data.index>"2009-12-31"]
data

,WTI,SP500,VIX,USD,Gold,Yield,Oil_Volatility,INDPRO
Date,,,,,,,,
2010-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,88.0221
2010-01-04,81.52,1132.989990,20.04,92.3566,1117.699951,2.19,35.439999,88.0221
2010-01-05,81.74,1136.520020,19.35,92.2236,1118.099976,2.20,34.270000,88.0221
2010-01-06,83.12,1137.140015,19.16,92.0941,1135.900024,2.25,34.400002,88.0221
2010-01-07,82.60,1141.689941,19.06,92.3684,1133.099976,2.23,33.610001,88.0221
...,...,...,...,...,...,...,...,...
2024-12-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99.4695
2024-12-26,70.38,6037.589844,14.73,128.3329,2638.800049,0.23,30.010000,99.4695
2024-12-27,71.28,5970.839844,15.95,128.4500,2617.199951,0.26,30.209999,99.4695
2024-12-30,71.73,5906.939941,17.40,128.8205,2606.100098,0.26,30.770000,99.4695
2024-12-31,72.44,NaN,17.35,129.2775,NaN,0.31,NaN,99.4695

In [113]:
data.to_csv("wti_data.csv", index=True)

In [ ]:
weekly_data = data.resample('W').last()

In [120]:
weekly_data

,WTI,SP500,VIX,USD,Gold,Yield,Oil_Volatility,INDPRO
Date,,,,,,,,
2010-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,88.0221
2010-01-10,82.74,1144.979980,18.13,92.1485,1138.199951,2.27,31.340000,88.0221
2010-01-17,77.96,1136.030029,17.91,91.7668,1130.099976,2.26,29.799999,88.3793
2010-01-24,74.25,1091.760010,27.31,92.9430,1089.199951,2.23,34.849998,88.3793
2010-01-31,72.85,1073.869995,24.62,93.7638,1083.000000,2.25,34.049999,88.3793
...,...,...,...,...,...,...,...,...
2024-12-08,68.58,6090.270020,12.77,126.6880,2638.600098,0.10,30.980000,99.4695
2024-12-15,71.54,6051.089844,13.81,127.3096,2656.000000,0.19,34.919998,99.4695
2024-12-22,69.71,5930.850098,18.36,127.8930,2628.699951,0.20,29.270000,99.4695
2024-12-29,71.28,5970.839844,15.95,128.4500,2617.199951,0.26,30.209999,99.4695
2025-01-05,72.44,5906.939941,17.35,129.2775,2606.100098,0.31,30.770000,99.4695

In [121]:
returns = np.log(weekly_data / weekly_data.shift(1))

c:\Users\komet\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\internals\blocks.py:347: RuntimeWarning: divide by zero encountered in log
  result = func(self.values, **kwargs)
c:\Users\komet\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\internals\blocks.py:347: RuntimeWarning: invalid value encountered in log
  result = func(self.values, **kwargs)

In [122]:
returns

,WTI,SP500,VIX,USD,Gold,Yield,Oil_Volatility,INDPRO
Date,,,,,,,,
2010-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00000
2010-01-17,-0.059507,-0.007847,-0.012209,-0.004151,-0.007142,-0.004415,-0.050387,0.00405
2010-01-24,-0.048758,-0.039749,0.421894,0.012736,-0.036863,-0.013363,0.156545,0.00000
2010-01-31,-0.019035,-0.016522,-0.103694,0.008792,-0.005708,0.008929,-0.023223,0.00000
...,...,...,...,...,...,...,...,...
2024-12-08,0.004677,0.009551,-0.056331,0.000854,-0.006949,0.223144,-0.120577,0.00000
2024-12-15,0.042256,-0.006454,0.078294,0.004895,0.006573,0.641854,0.119718,0.00000
2024-12-22,-0.025913,-0.020071,0.284781,0.004572,-0.010332,0.051293,-0.176497,0.00000
2024-12-29,0.022272,0.006720,-0.140716,0.004346,-0.004384,0.262364,0.031610,0.00000
2025-01-05,0.016143,-0.010760,0.084134,0.006422,-0.004250,0.175891,0.018367,0.00000

In [123]:
returns['INDPRO'] = data['INDPRO'].pct_change()

In [124]:
returns

,WTI,SP500,VIX,USD,Gold,Yield,Oil_Volatility,INDPRO
Date,,,,,,,,
2010-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
2010-01-17,-0.059507,-0.007847,-0.012209,-0.004151,-0.007142,-0.004415,-0.050387,0.004058
2010-01-24,-0.048758,-0.039749,0.421894,0.012736,-0.036863,-0.013363,0.156545,0.000000
2010-01-31,-0.019035,-0.016522,-0.103694,0.008792,-0.005708,0.008929,-0.023223,0.000000
...,...,...,...,...,...,...,...,...
2024-12-08,0.004677,0.009551,-0.056331,0.000854,-0.006949,0.223144,-0.120577,0.000000
2024-12-15,0.042256,-0.006454,0.078294,0.004895,0.006573,0.641854,0.119718,0.000000
2024-12-22,-0.025913,-0.020071,0.284781,0.004572,-0.010332,0.051293,-0.176497,0.000000
2024-12-29,0.022272,0.006720,-0.140716,0.004346,-0.004384,0.262364,0.031610,0.000000
2025-01-05,0.016143,-0.010760,0.084134,0.006422,-0.004250,0.175891,0.018367,0.000000

In [127]:
returns['WTI_lag1'] = returns['WTI'].shift(1)
returns['WTI_lag2'] = returns['WTI'].shift(2)

In [128]:
y = returns['WTI'].shift(-1)
X = returns.drop(columns=['WTI'])

In [126]:
y

Date
2010-01-03         NaN
2010-01-10   -0.059507
2010-01-17   -0.048758
2010-01-24   -0.019035
2010-01-31   -0.023612
                ...
2024-12-08    0.042256
2024-12-15   -0.025913
2024-12-22    0.022272
2024-12-29    0.016143
2025-01-05         NaN
Freq: W-SUN, Name: WTI, Length: 784, dtype: float64